{block content}

{include "../head.latte"}

<script type="text/javascript">
    jQuery(document).ready(function() {

		function setVisibility(){
			if($("#frmformMenuEdit-type").val() == "dir"){
				$("#par1").hide();
				$("#par3").hide();
				$("#par2").hide();
				$("#par4").hide();
				$("#linkto").hide();
				$("#frmformMenuEdit-uri").parent().parent().hide();
			}else if($("#frmformMenuEdit-type").val() == "link"){
				$("#par1").show();
				$("#par3").show();
				$("#par2").show();
				$("#par4").show();
				$("#linkto").show();
				$("#frmformMenuEdit-url").parent().parent().hide();
			}else{
				$("#frmformMenuEdit-url").parent().parent().show();
				$("#par1").hide();
				$("#par3").hide();
				$("#par2").hide();
				$("#par4").hide();
				$("#linkto").hide();
			}
		}

		$("#frmformMenuEdit-type").change(function(){
			setVisibility();
		})
		setVisibility();

    });
</script>

{control formMenuEdit}
